### PR TITLE
Read weather data from postgis and geotiff file

### PR DESCRIPTION
**Pull request by Kcheung42**
----

#

### CODE REVIEW

**Comment by sirmspencer** [comment]
org/GridFire.org
3011 add `This behavior is controlled as follows:`
3013, 3024 to be consistant with your other blocks use `To fetch weather`
3021, 3032 Should you show all four raster examples?
Should you show one or two raster examples in the `Configuration Examples` section

resources/import_weather_rasters.sh
This is not in GridFire.org
1/6 -U is username, update variable.

src/gridfire/cli.clj
4-9 align :as
10-13 align :refer
210 remove extra space
213 val is shadowing `src/gridfire/cli.clj`
213 I prefer to use get if you need the map first `(get config weather-type)` because if the map is wrong, you can get a error. Otherwise use the keyword first like you are doing elsewhere `(weather-type config)`.
215 use simulations instead of n
217 you dont need a let here.  Just return `(fetch/weather config weather-type)`

src/gridfire/fetch.clj
3-4 align :as
5-9 align :refer
102 type is shadowing (type ).  Use weather-type
103 You could just pass fetch-method instead of defining it twice (cli.clj 214)
```
(defmulti weather
  (fn [config fetch-method weather-type]
    (keyword (str (name (fetch-method config)) "-" (name weather-type)))))
```

src/gridfire/postgis_bridge.clj
3-5 align :as

src/gridfire/magellan_bridge.clj / src/gridfire/postgis_bridge.clj
42 geotiff-raster-to-matrix-multiband and postgis-raster-to-matrix-multiband have a very high level of overlapping code.  Do you need seperate functions?  You use the multiband version much more frequently so you could create a variadic fucntion to accept and optional single-band? param or just detect if its single or mutliband.  In postgis-raster-to-matrix you call ST_DumpValues(rast,1) but in postgis-raster-to-matrix-multiband you call ST_DumpValues(rast).  Can you use ST_DumpValues(rast) in both cases and see if you are getting single or multiband rasters? If you need them to be separate functions, factor out the common code.

test/gridfire/build_test_db.clj
37-44 you shouldnt need `sh` in these calls. sh/sh will use the system local shell. using sh make the call specific to machines that use sh by calling sh on top of the local shell.

test/gridfire/read_weather_test.clj
2-8 align requires.
74, 75, 100, 101, 126, 127 remove extra space after config

**Comment by Kcheung42** [comment]
org/GridFire.org
3013, 3024 to be consistant with your other blocks use `To fetch weather`
> 3021, 3032 Should you show all four raster examples?
Yes I can include this to be more thorough.

> Should you show one or two raster examples in the `Configuration Examples` section
Yes I should include these in the example with reading geotiffs from disk

src/gridfire/fetch.clj

>src/gridfire/magellan_bridge.clj / src/gridfire/postgis_bridge.clj
> 2 geotiff-raster-to-matrix-multiband and postgis-raster-to-matrix-multiband have a very high level of duplicate code.  Do you need seperate functions?  You use the multiband version much more frequently so you could create a variadic fucntion to accept and optional single-band? param or just detect if its single or mutliband.  For example, In postgis-raster-to-matrix you call ST_DumpValues(rast,1) but in postgis-raster-to-matrix-multiband you call ST_DumpValues(rast).  Can you use ST_DumpValues(rast) in both cases and see if you are getting single or multiband rasters? If you need them to be separate functions, factor out the common code.

I've refactored so that postgis-raster-to-matrix and
geotiff-raster-to-matrix will always return a multiband raster. Doing
this means whenever we expect a single band raster we need to filter
for the first band.

>test/gridfire/build_test_db.clj
>37-44 you shouldnt need `sh` in these calls. sh/sh will use the system local shell. using sh make the call specific to machines that use sh by calling sh on top of the local shell.

- I got permission issues when not using sh.

**Comment by sirmspencer** [comment]
org/GridFire.org
2956-2957 This is new text.  The line spacing makes this feel like it doesnt fit here.  All of your other block use the pattern descritption, list, example.  This would break that pattern.
2951, 2970 to be consistant with your other blocks use `To fetch weather`
2974, You dont use a period anywhere else in the list descriptions
3066 `layers, initial`
3040, 3092, your options list now include tif files from disk and tif files from Postgres
org/GridFire.org

src/gridfire/cli.clj
212, I like the condensed function.  You can reduce it further by removing the let binding.

src/gridfire/fetch.clj
60, 83, these were single band matrix before

gridfire/monte_carlo.clj
199-207 these were single band matrix before

**Comment by Kcheung42** [comment]
org/GridFire.org

on 2953,2954,2970,2971 I converted the `< >` brackets to `[ ]`since it
gave some funny characters when translating to gridfire.pdf. As a
Note, I should be updating gridfire.pdf but there's something wrong
with my tooling. It leaves out all the source code blocks.

>src/gridfire/fetch.clj
>60, 83, these were single band matrix before
Yes in `cli/-main` I've filtered for the first band (line 223)
and in `ignition_test.clj` (line 56)

>gridfire/monte_carlo.clj
>199-207 these were single band matrix before
This part of the code base I have not modified since we aren't using it.

**Comment by lambdatronic** [comment]
sample_geotiff_config.edn:
- Lines 31-38: I think we can do better than these `:fetch-*-method`
  attributes. Right now, the weather values can either be numbers,
  lists, or vectors. Maps and sets are unused at the moment in our
  syntax. Let's use this compact map-based format instead:

  ```clojure
  :temperature       {:type :geotiff :source "test/gridfire/resources/weather-test/tempf_to_sample.tif"}
  :relative-humidity {:type :postgis :source "weather.rh where rid=1"}
  ```

  If we generalize this behavior back to :landfire-layers and
  :ignition-layer, then we can drop :fetch-layer-method and
  :fetch-ignition-method as well. Not only would this simplify our
  config.edn files, but it would make it possible to grab LANDFIRE
  layers from a mixture of GeoTIFFs and PostGIS calls in the same
  simulation.

  For backwards compatibility, if a string is provided for a
  :landfire-layer, we can assume that the :type is :postgis. There's
  no need to provide this fallback behavior for :ignition-layer or the
  weather parameters though since they are all new.

- Lines 24-25: Update the file and Postgres documentation to use the {:type * :source *} syntax.

sample_postgis_cofig.edn:
- Lines 29-30: Update the file and Postgres documentation to use the {:type * :source *} syntax.

cli.clj:
- Line 8: You don't need clojure.string anymore (see my new `get-weather` function below).
- Line 11: Move `matrix-to-raster` to the next line.
- Lines 103-172: `run-simulations` has to be updated to correctly
  handle temperature, relative-humidity, wind-speed-20ft, and
  wind-from-direction matrices.
- Lines 211-214: Here's a new implementation of `get-weather` using
  the simplified map-based syntax I proposed for the config.edn files.
  ```clojure
  (defn get-weather [{:keys [simulations] :as config} rand-generator weather-type]
    (let [weather-spec (config weather-type)]
      (if (map? weather-spec)
        (fetch/weather config weather-spec)
        (draw-samples rand-generator simulations weather-spec))))
  ```

fetch.clj:
- Line 4: No need for clojure.string here.
- Lines 99-133: Using the new syntax and `get-weather` function, this
  multimethod code simplifies down to just this:
  ```clojure
  (defmulti weather
    (fn [_ {:keys [type]}] type))

  (defmethod weather :postgis
    [{:keys [db-spec]} {:keys [source]}]
    (:matrix (postgis-raster-to-matrix db-spec source)))

  (defmethod weather :geotiff
    [_ {:keys [source]}]
    (:matrix (geotiff-raster-to-matrix source)))
  ```

postgis_bridge.clj:
- Lines 10-20: Definitely don't do this. You are calling read-string
  on a potentially very large matrix and then performing string
  manipulation operations on its text representation. This is going to
  take a ton of time and severely slow down our model performance. You
  should be using `.getArray` as my previous code did.
  ```clojure
  (->> result
       :matrix
       (#(.getArray ^PgArray %))
       (m/emap #(or % -1.0))
       m/matrix)
  ```

cli_test.clj:
- Lines 142,178: Remove extra blank line.

**Comment by Kcheung42** [comment]
cli.clj:
> Lines 103-172: `run-simulations` has to be updated to correctly
> handle temperature, relative-humidity, wind-speed-20ft, and
> wind-from-direction matrices.
- This is done on the next PR. This PR only handles the reading of the
  new config. I wanted to keep the PRs small.

fetch.clj:
  - Can I also update ignition-layer and landfire-layers with the new
    compact input format in this PR? Including all the other relevant
    namespaces (tests, cli.clj, etc)? 

postgis_bridge.clj:
> Lines 10-20: Definitely don't do this. You are calling read-string
> on a potentially very large matrix and then performing string
> manipulation operations on its text representation. This is going to
> take a ton of time and severely slow down our model performance. You
> should be using `.getArray` as my previous code did.
> ```clojure
> (->> result
>      :matrix
>      (#(.getArray ^PgArray %))
>      (m/emap #(or % -1.0))
>      m/matrix)
> ```
  - I get an error when trying to use `.getArray` on this object. The
    object has changed because we are now using this SQL which returns
    a multi-band raster instead of a single band: (I'll be looking into
    this some more)
  ``` sql
  SELECT ST_DumpValues(rast) AS matrix FROM 
  ```
  >java.lang.ClassCastException: class org.postgresql.util.PGobject cannot be cast to class org.postgresql.jdbc.PgArray (org.postgresql.util.PGobject and org.postgresql.jdbc.PgArray are in unnamed module of loader 'app')

**Comment by lambdatronic** [comment]
sample_geotiff_config.edn:
- Line 31: :gotiff -> :geotiff
- Line 32: :geotiff -> :postgis
- Line 45: d_to_sample.tif -> wd_to_sample.tif

sample_postgis_cofig.edn:
- Line 3: Drop :fetch-layer-method attribute.
- Line 20: fbfm40 -> dem
- Line 22: slp -> fbfm40
- Line 24: dem -> slp
- Line 33: in one of five ways

postgis_bridge.clj:
- Lines 16-77: Unfortunately, your multi-band
  `postgis-raster-to-matrix` won't work when resolution and threshold
  are passed as it is currently written. This is because `ST_Rescale`
  operates on all bands at once, but `ST_MapAlgebra` and
  `ST_DumpValues` must have a band specified. Furthermore, when you
  nest `ST_MapAlgebra` within `ST_DumpValues`, `ST_MapAlgebra` takes
  the band as input and returns a single band result raster, which
  must then be referenced with band=1 in `ST_DumpValues`. Here is a
  single-arity implementation of `postgis-raster-to-matrix` that
  should handle single/multi band rasters with or without the optional
  resolution and threshold parameters:

  ```clojure
  ;; Remember to import java.util.UUID at the top of the file.
  (defn postgis-raster-to-matrix
    [db-spec table-name & [resolution threshold]]
    (jdbc/with-db-transaction [conn db-spec]
      (let [table-name      (if-not resolution
                              table-name
                              (let [rescaled-table-name (str "gridfire_" (subs (str (UUID/randomUUID)) 0 8))
                                    rescale-query       (format (str "CREATE TEMPORARY TABLE %s "
                                                                     "ON COMMIT DROP AS "
                                                                     "SELECT ST_Rescale(rast,%s,-%s,'NearestNeighbor') AS rast"
                                                                     "FROM %s")
                                                                rescaled-table-name resolution resolution table-name)]
                                ;; Create a temporary table to hold the rescaled raster.
                                ;; It will be dropped when the transaction completes.
                                (jdbc/query conn [rescale-query])
                                rescaled-table-name))
            meta-query      (format "SELECT (ST_Metadata(rast)).* FROM %s" table-name)
            metadata        (first (jdbc/query conn [meta-query]))
            threshold-query (format (str "ST_MapAlgebra(rast,band,NULL,"
                                         "'CASE WHEN [rast.val] < %s"
                                         " THEN 0.0 ELSE [rast.val] END')")
                                    threshold) ; FIXME: make sure this works for single and multi-band rasters
            data-query      (format (str "SELECT ST_DumpValues(%s,%s) AS matrix "
                                         "FROM generate_series(1,%s) AS band "
                                         "CROSS JOIN %s")
                                    (if threshold threshold-query "rast")
                                    (if threshold 1 "band")
                                    (:numbands metadata)
                                    table-name)
            matrix          (when-let [results (seq (jdbc/query conn [data-query]))]
                              (m/matrix (mapv extract-matrix results)))]
        (assoc metadata :matrix matrix))))
  ```

cli_test.clj:
- Lines 142,160: Drop :fetch-layer-method attribute.

ignition_test.clj:
- Line 21: Drop :fetch-layer-method attribute.

**Comment by Kcheung42** [comment]
postgis_bridge.clj:

- Received an Error when running this query
"CREATE TEMPORARY TABLE gridfire_7b4b6c3e ON COMMIT DROP AS SELECT ST_Rescale(rast,600,-600,'NearestNeighbor') AS rast FROM weather.ws WHERE rid=1"
>No results were returned by the query.

**Pull request merged**
