### PR TITLE
Extend Gridfire to use Rasters for ignition

### PR DESCRIPTION
**Pull request by Kcheung42**
----

#

### CODE REVIEW

**Comment by sirmspencer** [comment]
org/GridFire.org
350/355, 403/409 -U is username.  Update variable name.
1904 This comment is inconsistant.  Either show the map over mulitple lines like maps are normally defined. or use the format from 
1920 remove extra space
1990 This looks odd.  Are you doing the same thing as `(set (map :cell ignition-events))`? I dont see a form of (into ) that takes a map function as the second arument
1991 fix column alignment
2009 These are no longer constants because you added initial-ignition-site
2100/2137 `(assoc constants :initial-ignition-site initial-ignition-site)` seems simpler here. Although, should you be grouping constatns and non constants?
2108-2120 move the private functons to before the defmulti
2158 Postgresql, PostGIS
2158-2176 fix line lengths.  It looks like Gary is aiming for 70 chars
2247-2250 fix line lengths.  It looks like Gary is aiming for 70 chars
2293 Missing blank line above.
2674, 2743, 2745 PostGIS is not a database.  Use either "PostGIS enable Posgresql database" or just "Postgresql database"
2696 I dont think you mean PostGIS here
2716-2717 remove spaces after keys
2717, 2798-2804, 2812, 2847, 2861-2868, 2872, 2900, 2915-2921, 2925
   - End of line comments are 1 space and 1 `;` after the end of the code
   - Why are your trailing comments also in ()? In other text where the unit is secondary to a descriptor it makes sense, but here you only have the units listed.
2718 move } to previous line
2669-2746 fix line lengths for non block text.  It looks like Gary is aiming for 70 chars
2677 Postgresql
2699 what are these paths releative to?
2734 "For a list of values, a value from the list will be randomly selected in each simulation."
2735 "For a range of values, a value from the range [inclusive exclusive] will be randomly selected in each simulation."
2766 Remove space from end of line
2792 Missing blank line above
2795 Is there a way to link to your descirption of how to do each above?
2805, 2813 Move } to previous line
2812 remove extra space after keyword
2831, 2889 (optional) You could move the comment to the line above right after the {, `{;; Comment`
2923 This is now section 4
2927 This is now section 5

**Comment by Kcheung42** [comment]
- [ ] 1990 This looks odd.  Are you doing the same thing as `(set (map :cell ignition-events))`? I dont see a form of (into ) that takes a map function as the second arument
  - This was done prior to me. This is using the form (into to
  xform from). where the set is the `to` and `(map :cell)` is the
  transducer xform. I'm not too familiar with transducer, only
  knowing that it helps with composability. May need Gary's input here.

- [ ] 2009 These are no longer constants because you added initial-ignition-site
  - I chose "constant" because these values do not change for the
  duration of that simulation, so in `run-loops` context they are constants.
  But I see that is confusing as the calling function do change this from 
  simulation to simulation. Initially the inputs were seperate args and I 
  converted it to a map so it can be passed down to other functions more easily. Do
  you have a suggestion for another name?

- [ ] 2795 Is there a way to link to your descirption of how to do each above?
  - Do you think this is sufficent or needs more clarity?

**Comment by sirmspencer** [comment]
> * [ ]  1990 This looks odd.  Are you doing the same thing as `(set (map :cell ignition-events))`? I dont see a form of (into ) that takes a map function as the second arument
>   
>   * This was done prior to me. This is using the form (into to
>     xform from). where the set is the `to` and `(map :cell)` is the
>     transducer xform. I'm not too familiar with transducer, only
>     knowing that it helps with composability.  @lambdatronic , Could you help us understand?
- I see now.  And they do look the same.

> * [ ]  2009 These are no longer constants because you added initial-ignition-site
>   
>   * I chose "constant" because these values do not change for the
>     duration of that simulation, so in `run-loops` context they are constants.
>     But I see that is confusing as the calling function do change this from
>     simulation to simulation. Initially the inputs were seperate args and I
>     converted it to a map so it can be passed down to other functions more easily. Do
>     you have a suggestion for another name?

- Im looking at this again.  The discrepancy is that based on your function description for run-fire-spread, initial-ignition-site should already be part of the constants map, and not a separate param.  I see why you have them named constants, that is fine, the oddity is that you have to assoc in a param that should already be a part of that map.

> * [ ]  2795 Is there a way to link to your descirption of how to do each above?
>
>   * Do you think this is sufficent or needs more clarity?

Nevermind, it is currently sufficient. 

2835, 2891 Add a `**` header for the examples.  This is not longer section 5.

**Comment by sirmspencer** [comment]
resources/import_ignition_rasters.sh
This does not appear in gridfire.org
1/6 -U is username, update variable

resources/sample_geotiff_config.edn
46 move the closing } to the previous line

resources/sample_postgis_config.edn
50 move the closing } to the previous line

src/gridfire/cli.clj
16, 17 remove unused imports
192 initial-ignition-site should be part of the map to match your function description for run-fire-spread

src/gridfire/cli.clj
5, 6 remove unused imports
13, 17, :as config is unused, remove
21 config is unused, use _ to inicate an unused param
329 ignition-site is an unesseary binding
360 landfire-layers is unused

test/gridfire/ignition_test.clj
30-39 trailing comments use 1 ;

**Comment by lambdatronic** [comment]
deps.edn:
- Line 11: Change sig-gis/magellan version to use :mvn/version or :git/url.
- Line 13: cider-nrepl isn't a runtime dependency of GridFire and should be removed.

resources/import_ignition_rasters.sh:
- Line 3: Add a blank line after #!/bin/sh to match your other shell scripts.
- Lines 6-9: No need for a `for` loop here since there is only one LAYER value. Use this instead:
```sh
LAYER="ign"
raster2pgsql -I -C $LAYER.tif $SCHEMA.$LAYER | psql -h localhost -U $USERNAME
```
- NOTE: We also need to update the SRID for this ign raster in the
  PostGIS DB. One approach would be to pass an SRID arg to this script
  and use the `SELECT UpdateRasterSRID(...)` command. Another would be
  to try using the `-s $SRID` parameter to `raster2pgsql` and see if
  it works.

resources/import_landfire_rasters.sh:
- Line 9: Change `-t 100x100` to `-t auto` to allow `raster2pgsql` to compute an "optimal" tile size.
  
resources/sample_geotiff_config.edn:
- Line 15: ;; Section 2: Ignition data
- Line 28,34: Move :max-runtime and :ellipse-adjustment-factor to Section 4.
- Line 41: "_tile_100" -> "_from_raster_ignition"
  
resources/sample_postgis_config.edn:
- Line 19: ;; Section 2: Ignition data
- Lines 32,38: Move :max-runtime and :ellipse-adjustment-factor to Section 4.

resources/update_landfire_srids.sh:
- Line 11: No ; needed for single commands sent using `psql -c`.
- NOTE: Is there a reason we can't merge this code into
  import_landfire_rasters.sh, so we only need one script?
  
src/gridfire/cli.clj:
- Lines 10-12,25-83: Move `layer-names`, `convert-metrics`, and `fetch-landfire-layers` to fetch.clj.
- Line 179: This doesn't correctly handle the case in which
  ignition-raster, ignition-row, and ignition-col are nil in
  gridfire.edn, which is the case in which GridFire has to randomly
  select an ignition point. Use this instead:
  ```clojure
  initial-ignition-site (or ignition-raster
                            (and (ignition-row i)
                                 (ignition-col i)
                                 [(ignition-row i) (ignition-col i)]))
  ```
- Line 191: :num-cols should use `m/column-count`
- Lines 208,220: You can't include :ignition-raster in the outputs
  since this is a matrix data structure and the output map is going to
  be written as a single line in a CSV file.

src/gridfire/fire_spread.clj:
- Line 278: `initial-ignition-site` doesn't appear to be used by any
  calling functions and can be dropped from the returned map.
  `global-clock` and `ignited-cells` are also not used by the calling
  functions, but they do provide useful information. Lets remove them
  from the returned map and add a new parameter like so:
  ```clojure
  :exit-condition (if (seq ignited-cells) :max-runtime-reached :no-burnable-fuels)
  ```
  Add this `exit-condition` field to the output CSV.
- Line 289: -1 -> -1.0 (these are double matrices)
- Line 301: - landfire-layers: map containing these entries:
- Line 317: - map containing a :matrix field of type core.matrix 2D double array (0-2)
- Line 318: - nil (this causes GridFire to select a random ignition point)
- Line 367: Add a new binding for `perimeter-indices`:
  ```clojure
  perimeter-indices (filter #(burnable-neighbors? fire-spread-matrix
                                                  fuel-model-matrix
                                                  num-rows
                                                  num-cols
                                                  %)
                            non-zero-indices)
  ```
  This is to prevent you from wasting CPU cycles on running
  `compute-neighborhood-fire-spread-rates!` on interior cells in the
  burned area. Note that you'll need to extract `fuel-model-matrix`
  from the `constants` map. Alternatively, instead of filtering on
  `burnable-neighbors?`, I think the ign.tif file might have a
  different numeric value in cells that are burning on the perimeter,
  which you could simply pull out instead.
- Line 368: `non-zero-indices` -> `perimeter-indeces`

**Comment by Kcheung42** [comment]
resources/update_landfire_srids.sh:
> NOTE: Is there a reason we can't merge this code into
>  import_landfire_rasters.sh, so we only need one script?

- One advantage to not merging is the user, if their files have the appropriate
meta data, won't need to look up the SRID. raster2pgsql should automatically
pull the SRID from the meta data. I thought having raster2pgsql find the SRID
would be preferable and if the SRID doesn't exist then we'd use the update script.
But I see that we are silently letting the layer be imported with missing SRID.
I can merge it together for now but perhaps revisit and have the script do some
checking for the SRID and prompt for one if it is missing.

src/gridfire/fire_spread.clj:
  > I think the ign.tif file might have a different numeric value in cells that
  > are burning on the perimeter, which you could simply pull out instead.
  - The ign.tif only has two values, burned and un-burned. Same with phi.tif.

**Comment by lambdatronic** [comment]
resources/import_ignition_rasters.sh:
- Line 9: Is the SRID set correctly on the imported layer? If not,
  replace `raster2pgsql -s $SRID` with:
  ```sh
  psql -h localhost -U $USERNAME -c "SELECT UpdateRasterSRID('$SCHEMA'::name,'$LAYER'::name,'rast'::name,$SRID)"
  ```

resources/import_landfire_rasters.sh:
- Line 10: Is the SRID set correctly on the imported layers? If not,
  replace `raster2pgsql -s $SRID` with:
  ```sh
  psql -h localhost -U $USERNAME -c "SELECT UpdateRasterSRID('$SCHEMA'::name,'$LAYER'::name,'rast'::name,$SRID)"
  ```
  
resources/sample_postgis_config.edn:
- Line 19: Remove "and weather data"

src/gridfire/cli.clj:
- Lines 10-12: geotiff-raster-to-matrix, postgis-raster-to-matrix, and degrees-to-radians are no longer used.
- Line 133: m/col-count -> m/column-count
- Line 174: `fire-spread-results` is nil in this branch. You should return :no-fire-spread for :exit-condition here.

src/gridfire/fetch.clj:
- Line 5: Missing degrees-to-radians.
- Line 69: Remove unnecessary blank line.

src/gridfire/fire_spread.clj:
- Line 299: - `map containing of these entries:` -> `map containing these entries:`
- Line 365,372: perimiter -> perimeter
- Line 366: `fuel-model-matrix` is undefined here. You need to extract
  it from the `constants` map in its own `let` binding.

**Comment by sirmspencer** [comment]
src/gridfire/fire_spread.clj:
- Line 91 rothermel-fast-wrapper is defined twice
- Line 211 source is unused
- Line 222 cell is unused
- Line 249 initial-ignition-site

src/gridfire/fetch.clj:
- Line 37 The function landfire-layers is the same as the key it uses

**Comment by Kcheung42** [comment]
resources/import_ignition_rasters.sh:
> Line 9: Is the SRID set correctly on the imported layer? If not,
- raster2pgsql does correctly set the SRID.

resources/import_landfire_rasters.sh:
> Line 10: Is the SRID set correctly on the imported layers? If not,
- Yes it does.
  
src/gridfire/fire_spread.clj:
> Line 91 rothermel-fast-wrapper is defined twice
- One is defined as a memoize version of rothermel-fast-wrapper.

**Comment by lambdatronic** [comment]
fire_spread.clj:
- Line 367: No need to check `in-bounds?` since `non-zero-indices` is derived from `fire-spread-matrix`.
- Lines 374-376: Remove `prn` debugging statements.

ignition_test.clj:
- Lines 56,60: landfire-raster -> landfire-rasters
- Lines 82-102: *ignition-layers -> *ignition-layer (there's only one layer)

**Comment by lambdatronic** [comment]
GridFire.org:
- Line 361: Missing period. database name -> username
  To run the script, give it the username name, schema name, and srid we wish the layers to have.
- Line 399: Missing period and blank line.
- Line 406: Remove extra space.
- Lines 405-410: Update text to describe one raster, not multiple.
- Line 410: Add blank line.
- Line 423: username name -> username. Also add a blank line.
- Lines 1916-1921: Fix indentation and tangle.
- Lines 2174-2179:
  1. A simple Clojure interface to a Postgresql database, containing
     the PostGIS spatial extensions. This interface is described in
     Section [[PostGIS Bridge]].

  2. Magellan, a Clojure library for interacting with geospatial
     datasets. This interface is described in Section [[Magellan]].

  Section [[Command Line Interface]] describes GridFire's command line
  interface along with its input configuration file format, which
  allows users to select between the PostGIS and Magellan data import
  options easily.
- Lines 2263-2266:
  Reading raster layers from disk is performed by a single function,
  called *geotiff-raster-to-matrix*. Given the location of a GeoTIFF
  file, this function will read the raster into memory and return the
  same map of information as the *postgis-raster-to-matrix* function,
  described in the previous section.
- Lines 2607: Configuration File
- Line 2628: , or
- Line 2631: Postgersql -> Postgresql
- Line 2631: , include
- Lines 2633,2656,2685,2708,2719: Blank line before list.
- Line 2634: to our -> for our
- Lines 2635,2636: No period.
- Line 2654: from a Postgresql database include -> from GeoTIFF files, include
- Line 2679: Ignition data from which to build simulation inputs
- Lines 2090,2626,2681,2728: Gridfire -> GridFire
- Lines 2683,2703,2707,2718,2918: paremeter -> perimeter
- Line 2685: point, include
- Line 2687: lsit -> list
- Line 2689: For this method of ignition, values may be entered in one of three ways:
- Line 2695: Remove second "a range of values,".
- Line 2696: Missing period.
- Line 2703: raster, we have
- Line 2707: database,
- Lines 2711,2715,2721,2725: ignition-layers -> ignition-layer
- Line 2718: disk, include
- Lines 2715,2725: scar -> ign
- Line 2732: Blank line before #+begin_src block
- Line 2740: Landfire -> LANDFIRE  (and remember to tangle)
- Line 2828: For all the options in this section, you may enter values in one of
- Lines 2833,2839: Move :max-runtime and :ellipse-adjustment-factor to Section 4.
- Line 2846: Single ; for trailing comments.
- Line 2861: landfire -> LANDFIRE
- Line 2862: our PostGIS-enabled database with ignition points randomly sampled from a range
- Lines 2701,2832,2840,2865,2866,2915,2921,2922,2967,2971,2972: No spaces before #+ block markers.
- Lines 2917-2918: Here is a complete sample configuration for reading both the LANDFIRE layers and an initial burn perimeter from GeoTIFF files on disk.

**Comment by sirmspencer** [comment]
141 Postgres
411, you are only importing one raster.  You single tense.
Lines 2726,2741: ignition-layers -> ignition-layer
Line 2845: For all the options in this section, you may enter values in one of
Line 2879: our PostGIS-enabled database with ignition points randomly sampled from a range
Lines 2934: Here is a complete sample configuration for reading both the LANDFIRE layers and an initial burn perimeter from GeoTIFF files on disk.

**Pull request merged**
