### PR TITLE
Add multimethod for fetching landfire layers

### PR DESCRIPTION
**Pull request by Kcheung42**
----

Extending Gridfire's ability to read in rasters from disk.

#

### CODE REVIEW

**Comment by lambdatronic** [comment]
deps.edn:
- Line 11: Revert magellan coordinates to Clojars.
- Lines 13-15: What are these libs for? Remove them if they are not being used.
- Line 20: Indent :main-opts values under :extra-paths value.

sample_geotiff_config.edn:
- Line 4: Rename :layer-files to :landfire-layers.

sample_postgis_config.edn:
- Line 8: Revert :layer->table back to :landfire-layers to avoid breaking the existing API.
- Line 26: Add the period back at the end of this sentence.

update-landfire-srids.sh
- Rename file to update_landfire_srids.sh for consistency with the other shell scripts.
- Line 7: You didn't include an fbfm13.tif file in test/gridfire/resources/
- Line 9: psql -U gridfire -c \

cli.clj:
- Line 23: layers-kw -> layer-names
- Line 77-78: You are using a different meaning of scale here, I
  believe. The band's scale and offset tell you how to interpret the
  numerical values in each cell. For example, if scale=10, offset=100,
  and a given cell value is 5, then you should interpret that value as
  meaning 5*10+100=150. The scalex and scaley attributes that we need
  to return here are the cell size in georeferenced units (e.g., 30m x
  30m).
- Line 78: :scaly -> :scaley
- Lines 79-100: Your docstring promises to return :skewx and :skewy,
  so these should be uncommented. Use single semicolons for trailing
  comments and prepend FIXME or TODO to your "not used?" comments.
- Line 81: Move :matrix after :numbands to match the docstring.
- Line 97-115: Here's a collision-free implementation of the fetch-landfire-layers methods:
```clojure
(defmethod fetch-landfire-layers :postgis
  [{:keys [db-spec landfire-layers]}]
  (convert-metrics
   (reduce (fn [amap layer-name]
             (let [table-name (landfire-layers layer-name)]
               (assoc amap layer-name
                      (postgis-raster-to-matrix db-spec table-name))))
           {}
           layer-names)))

(defmethod fetch-landfire-layers :geotiff
  [{:keys [landfire-layers]}]
  (convert-metrics
   (reduce (fn [amap layer-name]
             (let [file-name (landfire-layers layer-name)]
               (assoc amap layer-name
                      (geotiff-raster-to-matrix file-name))))
           {}
           layer-names)))
```
- Line 204-259: Fix indentation.
- Line 289: envleope -> envelope
- Lines 290-300: :envelope is not an attribute returned by geotiff-raster-to-matrix. This simplifies as follows:
```clojure
(defn get-envelope
  [config landfire-layers]
  (let [{:keys [upperleftx upperlefty width height scalex scaley]} (landfire-layers :elevation)]
    (make-envelope (:srid config)
                   upperleftx
                   (+ upperlefty (* height scaley))
                   (* width scalex)
                   (* -1.0 height scaley))))
```
- Lines 320-336,338-339: Fix indentation.

build_test_db.clj:
- It looks like you still need to call update-srid.sh after import_rasters.sh.

import_rasters.sh:
- Add detangling comments to this file.
- Line 6: You didn't include an fbfm13.tif file in test/gridfire/resources/

update-srid.sh:
- This file is redundant with resources/update-landfire-srids.sh. Only
  one should exist. Also, follow the coding style from
  import_rasters.sh and update-landfire-srids.sh here and pull out
  DATABASE, SCHEMA, and SRID into local variables before the `for`
  loop.
- Rename file to update_srids.sh for consistency with the other shell scripts.
- Add detangling comments to this file.
- Line 2: Add a blank line before the `for` statement for consistency with the other shell scripts.
- Line 2: You didn't include an fbfm13.tif file in test/gridfire/resources/
- Line 5: psql -U gridfire_test -c \

**Comment by Kcheung42** [comment]
update-landfire-srids.sh:
- added `-h localhost` to get pass permission issues

cli.clj:
> Line 77-78: You are using a different meaning of scale here, I believe. The band's scale and offset tell you how to interpret the numerical values in each cell. For example, if scale=10, offset=100, and a given cell value is 5, then you should interpret that value as meaning 5*10+100=150. The scalex and scaley attributes that we need to return here are the cell size in georeferenced units (e.g., 30m x 30m).

- I did misunderstand this, thank you. I think now I should pull this info from
  the envelope's span in the x and y dimensions. I tested this to compare with
  what I get from postgis (30) vs geotiff (3000) should I always adjust this by
  a factor of 100?

build_test_db.clj:
- Now uses script from resources folder instead of test/resources

import_rasters.sh:
- Removed this file from test/resources

update-srid.sh:
- Removed this file from test/resources

**Comment by Kcheung42** [comment]
> Line 77-78: You are using a different meaning of scale here, I believe. The band's scale and offset tell you how to interpret the numerical values in each cell. For example, if scale=10, offset=100, and a given cell value is 5, then you should interpret that value as meaning 5*10+100=150. The scalex and scaley attributes that we need to return here are the cell size in georeferenced units (e.g., 30m x 30m).
 - I did misunderstand this, thank you. I think now I should pull this info from
  the envelope's span in the x and y dimensions. I tested this to compare with
  what I get from postgis (30) vs geotiff (3000) should I always adjust this by
  a factor of 100?

- edit: I don't think the span is the right way to get the resolution/cell-size. In a test with values from postgis, the scaley returned -30. I need to find the right place to get this information.

**Comment by Kcheung42** [comment]
cli.clj:

> Line 75: Make sure that `(get-in image [:origin :x])` equals `(get-in envelope [:x :min])`

They do not equal. image origin is [0 0] where as envelope is [-2067000.0 2457000.0]. I don't
understand from the docs what the coordinates mean in a RenderedImage. Since a RenderedImage
doesn't have CRS info, the coordinates I assume are Cartesian coordinates so [0 0] makes sense.

> Line 84: `:matrix (m/matrix matrix)` <-- matrix is always a primitive array
  and cannot contain nil or false.

> Line 299: Check the docs for org.geotools.geometry.Envelope2D and make sure that its constructor wants a positive height value as its 5th argument. As our code is currently written, `scaley` will always be negative, so `(* -1.0 height scaley)` will always be positive. Let's make sure that we aren't getting this backwards.

- Constructor accepts a negative number, but docs doesn't mention what that would mean.

- But when testing resample-raster-test in magellan with a negative height causes matrix-to-raster
to throw an error:
`java.lang.IllegalArgumentException: Envelope must be at least two-dimensional and non-empty.`

**Pull request merged**
